// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: font.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireFontBuildJob = `-- name: AcquireFontBuildJob :one
WITH leased AS (
    INSERT INTO font_build_jobs (
        artifact_key, status, attempts, locked_by, lease_until, started_at, updated_at
    ) VALUES (
        $1, 'running', 1, $2, now() + ($3::bigint * interval '1 millisecond'), now(), now()
    )
    ON CONFLICT (artifact_key) DO UPDATE
    SET
        status = 'running',
        attempts = font_build_jobs.attempts + 1,
        locked_by = EXCLUDED.locked_by,
        lease_until = now() + ($3::bigint * interval '1 millisecond'),
        error = NULL,
        started_at = now(),
        completed_at = NULL,
        updated_at = now()
    WHERE font_build_jobs.status IN ('pending', 'failed')
       OR (font_build_jobs.status = 'running' AND font_build_jobs.lease_until < now())
       OR (
            font_build_jobs.status = 'ready'
            AND EXISTS (
                SELECT 1 FROM font_artifacts AS current_artifact
                WHERE current_artifact.artifact_key = font_build_jobs.artifact_key
                  AND current_artifact.status IN ('missing', 'failed', 'stale')
            )
       )
    RETURNING artifact_key
), marked AS (
    UPDATE font_artifacts
    SET status = 'running', error = NULL, updated_at = now()
    WHERE artifact_key = $1 AND EXISTS (SELECT 1 FROM leased)
    RETURNING artifact_key
)
SELECT EXISTS(SELECT 1 FROM marked)::boolean AS acquired
`

type AcquireFontBuildJobParams struct {
	ArtifactKey string      `json:"artifact_key"`
	LockedBy    pgtype.Text `json:"locked_by"`
	Column3     int64       `json:"column_3"`
}

func (q *Queries) AcquireFontBuildJob(ctx context.Context, arg AcquireFontBuildJobParams) (bool, error) {
	row := q.db.QueryRow(ctx, acquireFontBuildJob, arg.ArtifactKey, arg.LockedBy, arg.Column3)
	var acquired bool
	err := row.Scan(&acquired)
	return acquired, err
}

const completeFontBuildJob = `-- name: CompleteFontBuildJob :execrows
UPDATE font_build_jobs
SET
    status = 'ready',
    locked_by = NULL,
    lease_until = NULL,
    error = NULL,
    completed_at = now(),
    updated_at = now()
WHERE artifact_key = $1
  AND status = 'running'
  AND locked_by = $2
  AND lease_until >= now()
`

func (q *Queries) CompleteFontBuildJob(ctx context.Context, artifactKey string, lockedBy pgtype.Text) (int64, error) {
	result, err := q.db.Exec(ctx, completeFontBuildJob, artifactKey, lockedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createFontArtifact = `-- name: CreateFontArtifact :exec
INSERT INTO font_artifacts (
    artifact_key,
    kind,
    status,
    family_id,
    weight,
    version,
    pack,
    word_hash,
    normalized_word_set,
    source_checksum_sha256,
    builder_version,
    object_key,
    content_type
) VALUES (
    $1, $2, $3, $4, $5, NULLIF($6, 0), NULLIF($7, ''), NULLIF($8, ''),
    NULLIF($9, ''), NULLIF($10, ''), $11, $12, $13
)
ON CONFLICT (artifact_key) DO NOTHING
`

type CreateFontArtifactParams struct {
	ArtifactKey    string      `json:"artifact_key"`
	Kind           string      `json:"kind"`
	Status         string      `json:"status"`
	FamilyID       string      `json:"family_id"`
	Weight         int16       `json:"weight"`
	Column6        interface{} `json:"column_6"`
	Column7        interface{} `json:"column_7"`
	Column8        interface{} `json:"column_8"`
	Column9        interface{} `json:"column_9"`
	Column10       interface{} `json:"column_10"`
	BuilderVersion string      `json:"builder_version"`
	ObjectKey      string      `json:"object_key"`
	ContentType    string      `json:"content_type"`
}

func (q *Queries) CreateFontArtifact(ctx context.Context, arg CreateFontArtifactParams) error {
	_, err := q.db.Exec(ctx, createFontArtifact,
		arg.ArtifactKey,
		arg.Kind,
		arg.Status,
		arg.FamilyID,
		arg.Weight,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.Column10,
		arg.BuilderVersion,
		arg.ObjectKey,
		arg.ContentType,
	)
	return err
}

const failFontBuildJob = `-- name: FailFontBuildJob :execrows
UPDATE font_build_jobs
SET
    status = 'failed',
    locked_by = NULL,
    lease_until = NULL,
    error = $3,
    completed_at = now(),
    updated_at = now()
WHERE artifact_key = $1 AND status = 'running' AND locked_by = $2
`

type FailFontBuildJobParams struct {
	ArtifactKey string      `json:"artifact_key"`
	LockedBy    pgtype.Text `json:"locked_by"`
	Error       pgtype.Text `json:"error"`
}

func (q *Queries) FailFontBuildJob(ctx context.Context, arg FailFontBuildJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, failFontBuildJob, arg.ArtifactKey, arg.LockedBy, arg.Error)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findStaticPacks = `-- name: FindStaticPacks :many
SELECT DISTINCT pack
FROM static_fonts
WHERE $1::text = ANY(families)
  AND char = ANY($2::text[])
ORDER BY pack
`

func (q *Queries) FindStaticPacks(ctx context.Context, column1 string, column2 []string) ([]int16, error) {
	rows, err := q.db.Query(ctx, findStaticPacks, column1, column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int16{}
	for rows.Next() {
		var pack int16
		if err := rows.Scan(&pack); err != nil {
			return nil, err
		}
		items = append(items, pack)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCurrentStaticVersion = `-- name: GetCurrentStaticVersion :one
SELECT bullet
FROM version
ORDER BY start DESC, bullet DESC
LIMIT 1
`

func (q *Queries) GetCurrentStaticVersion(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getCurrentStaticVersion)
	var bullet int32
	err := row.Scan(&bullet)
	return bullet, err
}

const getFontArtifact = `-- name: GetFontArtifact :one
SELECT
    artifact_key,
    kind,
    status,
    family_id,
    weight,
    COALESCE(version, 0)::int AS version,
    COALESCE(pack, '')::text AS pack,
    COALESCE(word_hash, '')::text AS word_hash,
    COALESCE(normalized_word_set, '')::text AS normalized_word_set,
    COALESCE(source_checksum_sha256, '')::text AS source_checksum_sha256,
    builder_version,
    object_key,
    content_type,
    size_bytes,
    COALESCE(etag, '')::text AS etag,
    COALESCE(checksum_sha256, '')::text AS checksum_sha256
FROM font_artifacts
WHERE artifact_key = $1
`

type GetFontArtifactRow struct {
	ArtifactKey          string `json:"artifact_key"`
	Kind                 string `json:"kind"`
	Status               string `json:"status"`
	FamilyID             string `json:"family_id"`
	Weight               int16  `json:"weight"`
	Version              int32  `json:"version"`
	Pack                 string `json:"pack"`
	WordHash             string `json:"word_hash"`
	NormalizedWordSet    string `json:"normalized_word_set"`
	SourceChecksumSha256 string `json:"source_checksum_sha256"`
	BuilderVersion       string `json:"builder_version"`
	ObjectKey            string `json:"object_key"`
	ContentType          string `json:"content_type"`
	SizeBytes            int64  `json:"size_bytes"`
	Etag                 string `json:"etag"`
	ChecksumSha256       string `json:"checksum_sha256"`
}

func (q *Queries) GetFontArtifact(ctx context.Context, artifactKey string) (GetFontArtifactRow, error) {
	row := q.db.QueryRow(ctx, getFontArtifact, artifactKey)
	var i GetFontArtifactRow
	err := row.Scan(
		&i.ArtifactKey,
		&i.Kind,
		&i.Status,
		&i.FamilyID,
		&i.Weight,
		&i.Version,
		&i.Pack,
		&i.WordHash,
		&i.NormalizedWordSet,
		&i.SourceChecksumSha256,
		&i.BuilderVersion,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Etag,
		&i.ChecksumSha256,
	)
	return i, err
}

const getFontFamily = `-- name: GetFontFamily :one
SELECT
    id,
    name,
    COALESCE(name_zh, '')::text AS name_zh,
    COALESCE(name_en, '')::text AS name_en,
    COALESCE(weights, ARRAY[]::SMALLINT[])::SMALLINT[] AS weights,
    COALESCE(license, '')::text AS license,
    COALESCE(version, '')::text AS version,
    COALESCE(description, '')::text AS description,
    COALESCE(category, '')::text AS category,
    COALESCE(family, '')::text AS family,
    COALESCE(tags, ARRAY[]::TEXT[])::TEXT[] AS tags,
    COALESCE(repo_url, '')::text AS repo_url,
    COALESCE(authors, ARRAY[]::TEXT[])::TEXT[] AS authors,
    COALESCE(format, 'ttf')::text AS format,
    COALESCE(demo_content_id, 0)::int AS demo_content_id
FROM font_family
WHERE id = $1
`

type GetFontFamilyRow struct {
	ID            string   `json:"id"`
	Name          string   `json:"name"`
	NameZh        string   `json:"name_zh"`
	NameEn        string   `json:"name_en"`
	Weights       []int16  `json:"weights"`
	License       string   `json:"license"`
	Version       string   `json:"version"`
	Description   string   `json:"description"`
	Category      string   `json:"category"`
	Family        string   `json:"family"`
	Tags          []string `json:"tags"`
	RepoUrl       string   `json:"repo_url"`
	Authors       []string `json:"authors"`
	Format        string   `json:"format"`
	DemoContentID int32    `json:"demo_content_id"`
}

func (q *Queries) GetFontFamily(ctx context.Context, id string) (GetFontFamilyRow, error) {
	row := q.db.QueryRow(ctx, getFontFamily, id)
	var i GetFontFamilyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameZh,
		&i.NameEn,
		&i.Weights,
		&i.License,
		&i.Version,
		&i.Description,
		&i.Category,
		&i.Family,
		&i.Tags,
		&i.RepoUrl,
		&i.Authors,
		&i.Format,
		&i.DemoContentID,
	)
	return i, err
}

const getFontSource = `-- name: GetFontSource :one
SELECT
    family_id,
    weight,
    format,
    object_key,
    COALESCE(checksum_sha256, '')::text AS checksum_sha256,
    size_bytes,
    COALESCE(source_version, '')::text AS source_version
FROM font_sources
WHERE family_id = $1 AND weight = $2
`

type GetFontSourceRow struct {
	FamilyID       string `json:"family_id"`
	Weight         int16  `json:"weight"`
	Format         string `json:"format"`
	ObjectKey      string `json:"object_key"`
	ChecksumSha256 string `json:"checksum_sha256"`
	SizeBytes      int64  `json:"size_bytes"`
	SourceVersion  string `json:"source_version"`
}

func (q *Queries) GetFontSource(ctx context.Context, familyID string, weight int16) (GetFontSourceRow, error) {
	row := q.db.QueryRow(ctx, getFontSource, familyID, weight)
	var i GetFontSourceRow
	err := row.Scan(
		&i.FamilyID,
		&i.Weight,
		&i.Format,
		&i.ObjectKey,
		&i.ChecksumSha256,
		&i.SizeBytes,
		&i.SourceVersion,
	)
	return i, err
}

const getStaticPackCharacters = `-- name: GetStaticPackCharacters :one
SELECT COALESCE(string_agg(char, '' ORDER BY char), '')::text AS characters
FROM static_fonts
WHERE pack = $1 AND $2::text = ANY(families)
`

func (q *Queries) GetStaticPackCharacters(ctx context.Context, pack int16, column2 string) (string, error) {
	row := q.db.QueryRow(ctx, getStaticPackCharacters, pack, column2)
	var characters string
	err := row.Scan(&characters)
	return characters, err
}

const listFontFamilies = `-- name: ListFontFamilies :many
SELECT
    id,
    name,
    COALESCE(name_zh, '')::text AS name_zh,
    COALESCE(name_en, '')::text AS name_en,
    COALESCE(weights, ARRAY[]::SMALLINT[])::SMALLINT[] AS weights,
    COALESCE(license, '')::text AS license,
    COALESCE(version, '')::text AS version,
    COALESCE(description, '')::text AS description,
    COALESCE(category, '')::text AS category,
    COALESCE(family, '')::text AS family,
    COALESCE(tags, ARRAY[]::TEXT[])::TEXT[] AS tags,
    COALESCE(repo_url, '')::text AS repo_url,
    COALESCE(authors, ARRAY[]::TEXT[])::TEXT[] AS authors,
    COALESCE(format, 'ttf')::text AS format,
    COALESCE(demo_content_id, 0)::int AS demo_content_id
FROM font_family
WHERE $1::text = ''
   OR id ILIKE '%' || $1 || '%'
   OR name ILIKE '%' || $1 || '%'
   OR COALESCE(name_zh, '') ILIKE '%' || $1 || '%'
   OR COALESCE(name_en, '') ILIKE '%' || $1 || '%'
   OR EXISTS (
        SELECT 1
        FROM unnest(COALESCE(authors, ARRAY[]::TEXT[])) AS author
        WHERE author ILIKE '%' || $1 || '%'
   )
ORDER BY id
`

type ListFontFamiliesRow struct {
	ID            string   `json:"id"`
	Name          string   `json:"name"`
	NameZh        string   `json:"name_zh"`
	NameEn        string   `json:"name_en"`
	Weights       []int16  `json:"weights"`
	License       string   `json:"license"`
	Version       string   `json:"version"`
	Description   string   `json:"description"`
	Category      string   `json:"category"`
	Family        string   `json:"family"`
	Tags          []string `json:"tags"`
	RepoUrl       string   `json:"repo_url"`
	Authors       []string `json:"authors"`
	Format        string   `json:"format"`
	DemoContentID int32    `json:"demo_content_id"`
}

func (q *Queries) ListFontFamilies(ctx context.Context, dollar_1 string) ([]ListFontFamiliesRow, error) {
	rows, err := q.db.Query(ctx, listFontFamilies, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFontFamiliesRow{}
	for rows.Next() {
		var i ListFontFamiliesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameZh,
			&i.NameEn,
			&i.Weights,
			&i.License,
			&i.Version,
			&i.Description,
			&i.Category,
			&i.Family,
			&i.Tags,
			&i.RepoUrl,
			&i.Authors,
			&i.Format,
			&i.DemoContentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFontArtifactFailed = `-- name: MarkFontArtifactFailed :execrows
UPDATE font_artifacts AS artifact
SET status = 'failed', error = $3, updated_at = now()
WHERE artifact.artifact_key = $1
  AND EXISTS (
      SELECT 1
      FROM font_build_jobs AS job
      WHERE job.artifact_key = artifact.artifact_key
        AND job.status = 'running'
        AND job.locked_by = $2
        AND job.lease_until >= now()
  )
`

type MarkFontArtifactFailedParams struct {
	ArtifactKey string      `json:"artifact_key"`
	LockedBy    pgtype.Text `json:"locked_by"`
	Error       pgtype.Text `json:"error"`
}

func (q *Queries) MarkFontArtifactFailed(ctx context.Context, arg MarkFontArtifactFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markFontArtifactFailed, arg.ArtifactKey, arg.LockedBy, arg.Error)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markFontArtifactMissing = `-- name: MarkFontArtifactMissing :exec
UPDATE font_artifacts
SET status = 'missing', error = $2, updated_at = now()
WHERE artifact_key = $1
`

func (q *Queries) MarkFontArtifactMissing(ctx context.Context, artifactKey string, error pgtype.Text) error {
	_, err := q.db.Exec(ctx, markFontArtifactMissing, artifactKey, error)
	return err
}

const markFontArtifactReady = `-- name: MarkFontArtifactReady :execrows
UPDATE font_artifacts AS artifact
SET
    status = 'ready',
    size_bytes = $3,
    etag = NULLIF($4, ''),
    checksum_sha256 = NULLIF($5, ''),
    error = NULL,
    last_verified_at = now(),
    updated_at = now()
WHERE artifact.artifact_key = $1
  AND EXISTS (
      SELECT 1
      FROM font_build_jobs AS job
      WHERE job.artifact_key = artifact.artifact_key
        AND job.status = 'running'
        AND job.locked_by = $2
        AND job.lease_until >= now()
  )
`

type MarkFontArtifactReadyParams struct {
	ArtifactKey string      `json:"artifact_key"`
	LockedBy    pgtype.Text `json:"locked_by"`
	SizeBytes   int64       `json:"size_bytes"`
	Column4     interface{} `json:"column_4"`
	Column5     interface{} `json:"column_5"`
}

func (q *Queries) MarkFontArtifactReady(ctx context.Context, arg MarkFontArtifactReadyParams) (int64, error) {
	result, err := q.db.Exec(ctx, markFontArtifactReady,
		arg.ArtifactKey,
		arg.LockedBy,
		arg.SizeBytes,
		arg.Column4,
		arg.Column5,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
