// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: font.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireFontBuildJob = `-- name: AcquireFontBuildJob :one
WITH quota AS MATERIALIZED (
    SELECT artifact_count, accounted_bytes
    FROM font_artifact_quota
    WHERE singleton
    FOR UPDATE
), locked_job AS MATERIALIZED (
    SELECT job.artifact_key
    FROM font_build_jobs AS job
    CROSS JOIN quota
    WHERE job.artifact_key = $1
      AND quota.artifact_count >= 0
    FOR UPDATE OF job
), eligible_artifact AS MATERIALIZED (
    SELECT artifact.artifact_key, artifact.reservation_bytes, artifact.quota_bytes
    FROM font_artifacts AS artifact
    CROSS JOIN (
        SELECT COUNT(*)::bigint AS locked_count
        FROM locked_job
    ) AS job_lock
    WHERE artifact.artifact_key = $1
      AND job_lock.locked_count >= 0
      AND (
          artifact.status IN ('pending', 'running', 'missing')
          OR (artifact.status = 'failed' AND artifact.failure_code IS NULL)
    )
    FOR UPDATE OF artifact
), admitted_artifact AS MATERIALIZED (
    SELECT eligible_artifact.artifact_key
    FROM eligible_artifact
    CROSS JOIN quota
    WHERE quota.artifact_count <= $2::bigint
      AND quota.accounted_bytes
            + GREATEST(eligible_artifact.reservation_bytes - eligible_artifact.quota_bytes, 0) <=
          $3::bigint
), leased AS (
    INSERT INTO font_build_jobs (
        artifact_key, status, attempts, fence, locked_by, lease_until, retryable, failure_code, started_at, updated_at
    ) SELECT
        admitted_artifact.artifact_key, 'running', 1, nextval('font_artifact_fence_seq'), $4,
        now() + ($5::bigint * interval '1 millisecond'), TRUE, NULL, now(), now()
    FROM admitted_artifact
    ON CONFLICT (artifact_key) DO UPDATE
    SET
        status = 'running',
        attempts = font_build_jobs.attempts + 1,
        fence = nextval('font_artifact_fence_seq'),
        locked_by = EXCLUDED.locked_by,
        lease_until = now() + ($5::bigint * interval '1 millisecond'),
        next_attempt_at = NULL,
        retryable = TRUE,
        failure_code = NULL,
        error = NULL,
        started_at = now(),
        completed_at = NULL,
        updated_at = now()
    WHERE EXISTS (SELECT 1 FROM admitted_artifact)
      AND (
          font_build_jobs.status = 'pending'
          OR (
            font_build_jobs.status = 'failed'
            AND font_build_jobs.retryable
            AND COALESCE(font_build_jobs.next_attempt_at, '-infinity'::timestamptz) <= now()
          )
          OR (font_build_jobs.status = 'running' AND font_build_jobs.lease_until < now())
          OR (
            font_build_jobs.status = 'ready'
          )
      )
    RETURNING artifact_key, fence
), marked AS (
    UPDATE font_artifacts AS artifact
    SET status = 'running', failure_code = NULL, retired_at = NULL, error = NULL, updated_at = now()
    FROM leased
    JOIN admitted_artifact USING (artifact_key)
    WHERE artifact.artifact_key = leased.artifact_key
    RETURNING leased.fence
)
SELECT fence FROM marked
`

type AcquireFontBuildJobParams struct {
	ArtifactKey       string      `json:"artifact_key"`
	MaxArtifacts      int64       `json:"max_artifacts"`
	MaxAccountedBytes int64       `json:"max_accounted_bytes"`
	LockedBy          pgtype.Text `json:"locked_by"`
	LeaseDurationMs   int64       `json:"lease_duration_ms"`
}

func (q *Queries) AcquireFontBuildJob(ctx context.Context, arg AcquireFontBuildJobParams) (int64, error) {
	row := q.db.QueryRow(ctx, acquireFontBuildJob,
		arg.ArtifactKey,
		arg.MaxArtifacts,
		arg.MaxAccountedBytes,
		arg.LockedBy,
		arg.LeaseDurationMs,
	)
	var fence int64
	err := row.Scan(&fence)
	return fence, err
}

const createFontArtifact = `-- name: CreateFontArtifact :one
WITH quota AS MATERIALIZED (
    SELECT artifact_count, accounted_bytes
    FROM font_artifact_quota
    WHERE singleton
    FOR UPDATE
), locked_job AS MATERIALIZED (
    SELECT job.artifact_key
    FROM font_build_jobs AS job
    CROSS JOIN quota
    WHERE job.artifact_key = $1
      AND quota.artifact_count >= 0
    FOR UPDATE OF job
), existing AS MATERIALIZED (
    SELECT
        current_artifact.artifact_key,
        current_artifact.status,
        current_artifact.size_bytes,
        current_artifact.reservation_bytes,
        current_artifact.quota_bytes,
        current_artifact.failure_code,
        (
            current_artifact.kind = $2
            AND current_artifact.family_id = $3
            AND current_artifact.weight = $4
            AND current_artifact.version IS NOT DISTINCT FROM NULLIF($5, 0)
            AND current_artifact.pack IS NOT DISTINCT FROM NULLIF($6, '')
            AND current_artifact.word_hash IS NOT DISTINCT FROM NULLIF($7, '')
            AND current_artifact.normalized_word_set IS NOT DISTINCT FROM NULLIF($8, '')
            AND current_artifact.source_checksum_sha256 IS NOT DISTINCT FROM NULLIF($9, '')
            AND current_artifact.builder_version = $10
            AND current_artifact.artifact_protocol_version = $11
            AND current_artifact.content_type = $12
        )::boolean AS compatible
    FROM font_artifacts AS current_artifact
    CROSS JOIN (
        SELECT COUNT(*)::bigint AS locked_count
        FROM locked_job
    ) AS job_lock
    WHERE current_artifact.artifact_key = $1
      AND job_lock.locked_count >= 0
    FOR UPDATE OF current_artifact
), existing_plan AS MATERIALIZED (
    SELECT
        existing.artifact_key, existing.status, existing.size_bytes, existing.reservation_bytes, existing.quota_bytes, existing.failure_code, existing.compatible,
        CASE
            WHEN existing.status = 'stale'
              OR existing.status IN ('pending', 'running', 'missing')
              OR (existing.status = 'failed' AND existing.failure_code IS NULL)
                THEN GREATEST(existing.reservation_bytes, $13::bigint)
            ELSE existing.reservation_bytes
        END::bigint AS target_reservation,
        CASE
            WHEN existing.status = 'stale' THEN
                GREATEST(existing.reservation_bytes, $13::bigint)
                    - existing.quota_bytes
            WHEN existing.status IN ('pending', 'running', 'missing') THEN
                GREATEST(existing.reservation_bytes, $13::bigint)
                    - existing.quota_bytes
            ELSE 0
        END::bigint AS accounted_increase
    FROM existing
), cached_failure AS MATERIALIZED (
    SELECT
        terminal_failure.artifact_key,
        (
            terminal_failure.kind = $2
            AND terminal_failure.family_id = $3
            AND terminal_failure.weight = $4
            AND terminal_failure.version IS NOT DISTINCT FROM NULLIF($5, 0)
            AND terminal_failure.pack IS NOT DISTINCT FROM NULLIF($6, '')
            AND terminal_failure.word_hash IS NOT DISTINCT FROM NULLIF($7, '')
            AND terminal_failure.normalized_word_set IS NOT DISTINCT FROM NULLIF($8, '')
            AND terminal_failure.source_checksum_sha256 IS NOT DISTINCT FROM NULLIF($9, '')
            AND terminal_failure.builder_version = $10
            AND terminal_failure.artifact_protocol_version = $11
            AND terminal_failure.content_type = $12
        )::boolean AS compatible
    FROM font_terminal_failures AS terminal_failure
    CROSS JOIN (
        SELECT COUNT(*)::bigint AS locked_count
        FROM existing
    ) AS artifact_lock
    WHERE terminal_failure.artifact_key = $1
      AND artifact_lock.locked_count >= 0
    FOR UPDATE OF terminal_failure
), admission AS MATERIALIZED (
    SELECT CASE
        WHEN existing_plan.artifact_key IS NOT NULL AND cached_failure.artifact_key IS NOT NULL THEN 'conflict'
        WHEN existing_plan.artifact_key IS NOT NULL AND NOT existing_plan.compatible THEN 'conflict'
        WHEN cached_failure.artifact_key IS NOT NULL AND NOT cached_failure.compatible THEN 'conflict'
        WHEN cached_failure.artifact_key IS NOT NULL THEN 'terminal'
        WHEN existing_plan.artifact_key IS NOT NULL
             AND existing_plan.accounted_increase > 0
             AND quota.accounted_bytes + existing_plan.accounted_increase >
                 $14::bigint THEN 'capacity'
        WHEN existing_plan.artifact_key IS NOT NULL THEN 'existing'
        WHEN quota.artifact_count >= $15::bigint THEN 'capacity'
        WHEN quota.accounted_bytes + $13::bigint >
             $14::bigint THEN 'capacity'
        ELSE 'new'
    END::text AS outcome
    FROM quota
    LEFT JOIN existing_plan ON TRUE
    LEFT JOIN cached_failure ON TRUE
), inserted AS (
INSERT INTO font_artifacts (
    artifact_key,
    kind,
    status,
    family_id,
    weight,
    version,
    pack,
    word_hash,
    normalized_word_set,
    source_checksum_sha256,
    builder_version,
    artifact_protocol_version,
    object_key,
    content_type,
    reservation_bytes
) SELECT
    $1, $2, $16, $3, $4,
    NULLIF($5, 0), NULLIF($6, ''), NULLIF($7, ''),
    NULLIF($8, ''), NULLIF($9, ''),
    $10, $11, $17, $12,
    $13
FROM admission
WHERE admission.outcome = 'new'
ON CONFLICT DO NOTHING
RETURNING artifact_key
), updated AS (
UPDATE font_artifacts AS artifact
SET
    status = CASE WHEN artifact.status = 'stale' THEN 'pending' ELSE artifact.status END,
    failure_code = CASE WHEN artifact.status = 'stale' THEN NULL ELSE artifact.failure_code END,
    retired_at = CASE WHEN artifact.status = 'stale' THEN NULL ELSE artifact.retired_at END,
    reservation_bytes = existing_plan.target_reservation,
    updated_at = CASE WHEN artifact.status = 'stale' THEN now() ELSE artifact.updated_at END
FROM existing_plan
JOIN admission ON admission.outcome = 'existing'
WHERE artifact.artifact_key = existing_plan.artifact_key
RETURNING artifact.artifact_key
), reset_reactivated_job AS (
    UPDATE font_build_jobs AS job
    SET
        status = 'pending',
        attempts = 0,
        locked_by = NULL,
        lease_until = NULL,
        next_attempt_at = NULL,
        retryable = TRUE,
        failure_code = NULL,
        error = NULL,
        started_at = NULL,
        completed_at = NULL,
        updated_at = now()
    FROM existing_plan
    JOIN updated USING (artifact_key)
    WHERE existing_plan.status = 'stale'
      AND job.artifact_key = existing_plan.artifact_key
    RETURNING job.artifact_key
)
SELECT CASE
    WHEN admission.outcome = 'capacity' THEN 'capacity'
    WHEN admission.outcome = 'conflict' THEN 'conflict'
    WHEN admission.outcome = 'terminal' THEN 'terminal'
    WHEN admission.outcome = 'new' AND inserted.artifact_key IS NULL THEN 'conflict'
    WHEN admission.outcome = 'existing' AND updated.artifact_key IS NULL THEN 'conflict'
    ELSE 'admitted'
END::text AS result
FROM admission
LEFT JOIN inserted ON TRUE
LEFT JOIN updated ON TRUE
`

type CreateFontArtifactParams struct {
	ArtifactKey             string      `json:"artifact_key"`
	Kind                    string      `json:"kind"`
	FamilyID                string      `json:"family_id"`
	Weight                  int16       `json:"weight"`
	Version                 interface{} `json:"version"`
	Pack                    interface{} `json:"pack"`
	WordHash                interface{} `json:"word_hash"`
	NormalizedWordSet       interface{} `json:"normalized_word_set"`
	SourceChecksumSha256    interface{} `json:"source_checksum_sha256"`
	BuilderVersion          string      `json:"builder_version"`
	ArtifactProtocolVersion string      `json:"artifact_protocol_version"`
	ContentType             string      `json:"content_type"`
	ArtifactReservation     int64       `json:"artifact_reservation"`
	MaxAccountedBytes       int64       `json:"max_accounted_bytes"`
	MaxArtifacts            int64       `json:"max_artifacts"`
	Status                  string      `json:"status"`
	ObjectKey               string      `json:"object_key"`
}

func (q *Queries) CreateFontArtifact(ctx context.Context, arg CreateFontArtifactParams) (string, error) {
	row := q.db.QueryRow(ctx, createFontArtifact,
		arg.ArtifactKey,
		arg.Kind,
		arg.FamilyID,
		arg.Weight,
		arg.Version,
		arg.Pack,
		arg.WordHash,
		arg.NormalizedWordSet,
		arg.SourceChecksumSha256,
		arg.BuilderVersion,
		arg.ArtifactProtocolVersion,
		arg.ContentType,
		arg.ArtifactReservation,
		arg.MaxAccountedBytes,
		arg.MaxArtifacts,
		arg.Status,
		arg.ObjectKey,
	)
	var result string
	err := row.Scan(&result)
	return result, err
}

const deleteRetiredFontArtifacts = `-- name: DeleteRetiredFontArtifacts :execrows
WITH quota AS MATERIALIZED (
    SELECT artifact_count
    FROM font_artifact_quota
    WHERE singleton
    FOR UPDATE
), locked_job_candidates AS MATERIALIZED (
    SELECT job.artifact_key, artifact.retired_at
    FROM font_build_jobs AS job
    JOIN font_artifacts AS artifact ON artifact.artifact_key = job.artifact_key
    CROSS JOIN quota
    WHERE artifact.status = 'stale'
      AND artifact.retired_at < $1::timestamptz
      AND quota.artifact_count >= 0
    ORDER BY artifact.retired_at, artifact.artifact_key
    LIMIT $2::int
    FOR UPDATE OF job SKIP LOCKED
), no_job_candidates AS MATERIALIZED (
    SELECT artifact.artifact_key, artifact.retired_at
    FROM font_artifacts AS artifact
    CROSS JOIN quota
    WHERE quota.artifact_count >= 0
      AND artifact.status = 'stale'
      AND artifact.retired_at < $1::timestamptz
      AND NOT EXISTS (
          SELECT 1
          FROM font_build_jobs AS job
          WHERE job.artifact_key = artifact.artifact_key
      )
    ORDER BY artifact.retired_at, artifact.artifact_key
    LIMIT $2::int
), selected_candidates AS MATERIALIZED (
    SELECT candidate_pool.artifact_key, candidate_pool.retired_at
    FROM (
        SELECT artifact_key, retired_at FROM locked_job_candidates
        UNION ALL
        SELECT artifact_key, retired_at FROM no_job_candidates
    ) AS candidate_pool
    ORDER BY candidate_pool.retired_at, candidate_pool.artifact_key
    LIMIT $2::int
), candidates AS MATERIALIZED (
    SELECT artifact.artifact_key
    FROM font_artifacts AS artifact
    JOIN selected_candidates USING (artifact_key)
    WHERE artifact.status = 'stale'
      AND artifact.retired_at < $1::timestamptz
      AND (
          EXISTS (
              SELECT 1 FROM locked_job_candidates AS locked_job
              WHERE locked_job.artifact_key = artifact.artifact_key
          )
          OR NOT EXISTS (
              SELECT 1 FROM font_build_jobs AS job
              WHERE job.artifact_key = artifact.artifact_key
          )
      )
    ORDER BY selected_candidates.retired_at, artifact.artifact_key
    FOR UPDATE OF artifact SKIP LOCKED
)
DELETE FROM font_artifacts AS artifact
USING candidates
WHERE artifact.artifact_key = candidates.artifact_key
  AND artifact.status = 'stale'
  AND artifact.retired_at < $1::timestamptz
`

func (q *Queries) DeleteRetiredFontArtifacts(ctx context.Context, retiredBefore pgtype.Timestamptz, batchSize int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRetiredFontArtifacts, retiredBefore, batchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failFontBuildJob = `-- name: FailFontBuildJob :execrows
WITH quota AS MATERIALIZED (
    SELECT artifact_count
    FROM font_artifact_quota
    WHERE singleton
    FOR UPDATE
), failed_job AS (
    UPDATE font_build_jobs AS job
    SET
        status = 'failed',
        locked_by = NULL,
        lease_until = NULL,
        next_attempt_at = now() + (
            LEAST(300::bigint, 1::bigint << LEAST(GREATEST(job.attempts - 1, 0), 9)::integer)
            * interval '1 second'
        ),
        retryable = TRUE,
        failure_code = NULL,
        error = $1,
        completed_at = now(),
        updated_at = now()
    FROM quota
    WHERE job.artifact_key = $2
      AND job.status = 'running'
      AND job.locked_by = $3
      AND job.fence = $4
      AND job.lease_until >= now()
      AND quota.artifact_count >= 0
    RETURNING job.artifact_key
)
UPDATE font_artifacts AS artifact
SET status = 'failed', failure_code = NULL, error = $1, updated_at = now()
WHERE artifact.artifact_key = $2
  AND EXISTS (SELECT 1 FROM failed_job)
`

type FailFontBuildJobParams struct {
	Error       pgtype.Text `json:"error"`
	ArtifactKey string      `json:"artifact_key"`
	LockedBy    pgtype.Text `json:"locked_by"`
	Fence       int64       `json:"fence"`
}

func (q *Queries) FailFontBuildJob(ctx context.Context, arg FailFontBuildJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, failFontBuildJob,
		arg.Error,
		arg.ArtifactKey,
		arg.LockedBy,
		arg.Fence,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failFontBuildJobTerminal = `-- name: FailFontBuildJobTerminal :execrows
WITH quota AS MATERIALIZED (
    SELECT artifact_count
    FROM font_artifact_quota
    WHERE singleton
    FOR UPDATE
), claimed_job AS MATERIALIZED (
    SELECT job.artifact_key
    FROM font_build_jobs AS job
    CROSS JOIN quota
    WHERE job.artifact_key = $1
      AND job.status = 'running'
      AND job.locked_by = $2
      AND job.fence = $3
      AND job.lease_until >= now()
      AND quota.artifact_count >= 0
    FOR UPDATE OF job
), candidate AS MATERIALIZED (
    SELECT
        artifact.artifact_key,
        artifact.kind,
        artifact.family_id,
        artifact.weight,
        artifact.version,
        artifact.pack,
        artifact.word_hash,
        artifact.normalized_word_set,
        artifact.source_checksum_sha256,
        artifact.builder_version,
        artifact.artifact_protocol_version,
        artifact.content_type
    FROM font_artifacts AS artifact
    JOIN claimed_job USING (artifact_key)
    WHERE artifact.artifact_key = $1
      AND artifact.status = 'running'
    FOR UPDATE OF artifact
), eviction_candidates AS MATERIALIZED (
    SELECT terminal_failure.artifact_key
    FROM font_terminal_failures AS terminal_failure
    WHERE EXISTS (SELECT 1 FROM candidate)
    ORDER BY terminal_failure.cached_at, terminal_failure.artifact_key
    LIMIT (
        SELECT GREATEST(
            COUNT(*) - $4::bigint + 1,
            0
        )::bigint
        FROM font_terminal_failures
    )
    FOR UPDATE OF terminal_failure
), evicted AS (
    DELETE FROM font_terminal_failures AS terminal_failure
    USING eviction_candidates
    WHERE terminal_failure.artifact_key = eviction_candidates.artifact_key
    RETURNING terminal_failure.artifact_key
), cached AS (
    INSERT INTO font_terminal_failures (
        artifact_key,
        kind,
        family_id,
        weight,
        version,
        pack,
        word_hash,
        normalized_word_set,
        source_checksum_sha256,
        builder_version,
        artifact_protocol_version,
        content_type,
        failure_code,
        error,
        cached_at
    )
    SELECT
        candidate.artifact_key,
        candidate.kind,
        candidate.family_id,
        candidate.weight,
        candidate.version,
        candidate.pack,
        candidate.word_hash,
        candidate.normalized_word_set,
        candidate.source_checksum_sha256,
        candidate.builder_version,
        candidate.artifact_protocol_version,
        candidate.content_type,
        $5,
        $6,
        now()
    FROM candidate
    CROSS JOIN (
        SELECT COUNT(*)::bigint AS evicted_count
        FROM evicted
    ) AS eviction_barrier
    WHERE eviction_barrier.evicted_count >= 0
    ON CONFLICT (artifact_key) DO UPDATE
    SET
        kind = EXCLUDED.kind,
        family_id = EXCLUDED.family_id,
        weight = EXCLUDED.weight,
        version = EXCLUDED.version,
        pack = EXCLUDED.pack,
        word_hash = EXCLUDED.word_hash,
        normalized_word_set = EXCLUDED.normalized_word_set,
        source_checksum_sha256 = EXCLUDED.source_checksum_sha256,
        builder_version = EXCLUDED.builder_version,
        artifact_protocol_version = EXCLUDED.artifact_protocol_version,
        content_type = EXCLUDED.content_type,
        failure_code = EXCLUDED.failure_code,
        error = EXCLUDED.error,
        cached_at = EXCLUDED.cached_at
    RETURNING artifact_key
)
DELETE FROM font_artifacts AS artifact
USING cached
WHERE artifact.artifact_key = cached.artifact_key
`

type FailFontBuildJobTerminalParams struct {
	ArtifactKey         string      `json:"artifact_key"`
	LockedBy            pgtype.Text `json:"locked_by"`
	Fence               int64       `json:"fence"`
	MaxTerminalFailures int64       `json:"max_terminal_failures"`
	FailureCode         string      `json:"failure_code"`
	Error               pgtype.Text `json:"error"`
}

func (q *Queries) FailFontBuildJobTerminal(ctx context.Context, arg FailFontBuildJobTerminalParams) (int64, error) {
	result, err := q.db.Exec(ctx, failFontBuildJobTerminal,
		arg.ArtifactKey,
		arg.LockedBy,
		arg.Fence,
		arg.MaxTerminalFailures,
		arg.FailureCode,
		arg.Error,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findReferencedFontObjectKeys = `-- name: FindReferencedFontObjectKeys :many
SELECT referenced.object_key
FROM (
    SELECT artifact.object_key
    FROM font_artifacts AS artifact
    WHERE artifact.object_key = ANY($1::text[])
    UNION
    SELECT source.object_key
    FROM font_sources AS source
    WHERE source.object_key = ANY($1::text[])
) AS referenced
ORDER BY referenced.object_key
`

func (q *Queries) FindReferencedFontObjectKeys(ctx context.Context, objectKeys []string) ([]string, error) {
	rows, err := q.db.Query(ctx, findReferencedFontObjectKeys, objectKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var object_key string
		if err := rows.Scan(&object_key); err != nil {
			return nil, err
		}
		items = append(items, object_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFontArtifact = `-- name: GetFontArtifact :one
WITH matching_artifact AS (
SELECT
    active_artifact.artifact_key,
    active_artifact.kind,
    active_artifact.status,
    active_artifact.family_id,
    active_artifact.weight,
    COALESCE(active_artifact.version, 0)::int AS version,
    COALESCE(active_artifact.pack, '')::text AS pack,
    COALESCE(active_artifact.word_hash, '')::text AS word_hash,
    COALESCE(active_artifact.normalized_word_set, '')::text AS normalized_word_set,
    COALESCE(active_artifact.source_checksum_sha256, '')::text AS source_checksum_sha256,
    active_artifact.builder_version,
    active_artifact.artifact_protocol_version,
    active_artifact.object_key,
    COALESCE(active_artifact.object_version_id, '')::text AS object_version_id,
    active_artifact.content_type,
    active_artifact.size_bytes,
    COALESCE(active_artifact.etag, '')::text AS etag,
    COALESCE(active_artifact.checksum_sha256, '')::text AS checksum_sha256,
    active_artifact.generation,
    COALESCE(active_artifact.failure_code, '')::text AS failure_code,
    0::smallint AS cache_rank
FROM font_artifacts AS active_artifact
WHERE active_artifact.artifact_key = $1
UNION ALL
SELECT
    terminal_failure.artifact_key,
    terminal_failure.kind,
    'failed'::text AS status,
    terminal_failure.family_id,
    terminal_failure.weight,
    COALESCE(terminal_failure.version, 0)::int AS version,
    COALESCE(terminal_failure.pack, '')::text AS pack,
    COALESCE(terminal_failure.word_hash, '')::text AS word_hash,
    COALESCE(terminal_failure.normalized_word_set, '')::text AS normalized_word_set,
    COALESCE(terminal_failure.source_checksum_sha256, '')::text AS source_checksum_sha256,
    terminal_failure.builder_version,
    terminal_failure.artifact_protocol_version,
    ''::text AS object_key,
    ''::text AS object_version_id,
    terminal_failure.content_type,
    0::bigint AS size_bytes,
    ''::text AS etag,
    ''::text AS checksum_sha256,
    0::bigint AS generation,
    terminal_failure.failure_code,
    1::smallint AS cache_rank
FROM font_terminal_failures AS terminal_failure
WHERE terminal_failure.artifact_key = $1
)
SELECT
    artifact_key,
    kind,
    status,
    family_id,
    weight,
    version,
    pack,
    word_hash,
    normalized_word_set,
    source_checksum_sha256,
    builder_version,
    artifact_protocol_version,
    object_key,
    object_version_id,
    content_type,
    size_bytes,
    etag,
    checksum_sha256,
    generation,
    failure_code
FROM matching_artifact
ORDER BY cache_rank
LIMIT 1
`

type GetFontArtifactRow struct {
	ArtifactKey             string `json:"artifact_key"`
	Kind                    string `json:"kind"`
	Status                  string `json:"status"`
	FamilyID                string `json:"family_id"`
	Weight                  int16  `json:"weight"`
	Version                 int32  `json:"version"`
	Pack                    string `json:"pack"`
	WordHash                string `json:"word_hash"`
	NormalizedWordSet       string `json:"normalized_word_set"`
	SourceChecksumSha256    string `json:"source_checksum_sha256"`
	BuilderVersion          string `json:"builder_version"`
	ArtifactProtocolVersion string `json:"artifact_protocol_version"`
	ObjectKey               string `json:"object_key"`
	ObjectVersionID         string `json:"object_version_id"`
	ContentType             string `json:"content_type"`
	SizeBytes               int64  `json:"size_bytes"`
	Etag                    string `json:"etag"`
	ChecksumSha256          string `json:"checksum_sha256"`
	Generation              int64  `json:"generation"`
	FailureCode             string `json:"failure_code"`
}

func (q *Queries) GetFontArtifact(ctx context.Context, artifactKey string) (GetFontArtifactRow, error) {
	row := q.db.QueryRow(ctx, getFontArtifact, artifactKey)
	var i GetFontArtifactRow
	err := row.Scan(
		&i.ArtifactKey,
		&i.Kind,
		&i.Status,
		&i.FamilyID,
		&i.Weight,
		&i.Version,
		&i.Pack,
		&i.WordHash,
		&i.NormalizedWordSet,
		&i.SourceChecksumSha256,
		&i.BuilderVersion,
		&i.ArtifactProtocolVersion,
		&i.ObjectKey,
		&i.ObjectVersionID,
		&i.ContentType,
		&i.SizeBytes,
		&i.Etag,
		&i.ChecksumSha256,
		&i.Generation,
		&i.FailureCode,
	)
	return i, err
}

const getFontBuildRetryAfterSeconds = `-- name: GetFontBuildRetryAfterSeconds :one
SELECT LEAST(
    300::bigint,
    GREATEST(
        1::bigint,
        COALESCE(CEIL(EXTRACT(EPOCH FROM (
            CASE
                WHEN status = 'running' THEN lease_until
                WHEN status = 'failed' THEN next_attempt_at
                ELSE NULL
            END - now()
        )))::bigint, 1::bigint)
    )
)::bigint AS retry_after_seconds
FROM font_build_jobs
WHERE artifact_key = $1
`

func (q *Queries) GetFontBuildRetryAfterSeconds(ctx context.Context, artifactKey string) (int64, error) {
	row := q.db.QueryRow(ctx, getFontBuildRetryAfterSeconds, artifactKey)
	var retry_after_seconds int64
	err := row.Scan(&retry_after_seconds)
	return retry_after_seconds, err
}

const getFontFamily = `-- name: GetFontFamily :one
SELECT
    id,
    name,
    COALESCE(name_zh, '')::text AS name_zh,
    COALESCE(name_en, '')::text AS name_en,
    COALESCE(weights, ARRAY[]::SMALLINT[])::SMALLINT[] AS weights,
    COALESCE(license, '')::text AS license,
    COALESCE(version, '')::text AS version,
    COALESCE(description, '')::text AS description,
    COALESCE(category, '')::text AS category,
    COALESCE(family, '')::text AS family,
    COALESCE(tags, ARRAY[]::TEXT[])::TEXT[] AS tags,
    COALESCE(repo_url, '')::text AS repo_url,
    COALESCE(authors, ARRAY[]::TEXT[])::TEXT[] AS authors,
    COALESCE(format, 'ttf')::text AS format,
    COALESCE(demo_content_id, 0)::int AS demo_content_id
FROM font_family
WHERE id = $1
`

type GetFontFamilyRow struct {
	ID            string   `json:"id"`
	Name          string   `json:"name"`
	NameZh        string   `json:"name_zh"`
	NameEn        string   `json:"name_en"`
	Weights       []int16  `json:"weights"`
	License       string   `json:"license"`
	Version       string   `json:"version"`
	Description   string   `json:"description"`
	Category      string   `json:"category"`
	Family        string   `json:"family"`
	Tags          []string `json:"tags"`
	RepoUrl       string   `json:"repo_url"`
	Authors       []string `json:"authors"`
	Format        string   `json:"format"`
	DemoContentID int32    `json:"demo_content_id"`
}

func (q *Queries) GetFontFamily(ctx context.Context, id string) (GetFontFamilyRow, error) {
	row := q.db.QueryRow(ctx, getFontFamily, id)
	var i GetFontFamilyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameZh,
		&i.NameEn,
		&i.Weights,
		&i.License,
		&i.Version,
		&i.Description,
		&i.Category,
		&i.Family,
		&i.Tags,
		&i.RepoUrl,
		&i.Authors,
		&i.Format,
		&i.DemoContentID,
	)
	return i, err
}

const getFontSource = `-- name: GetFontSource :one
SELECT
    family_id,
    weight,
    format,
    object_key,
    COALESCE(checksum_sha256, '')::text AS checksum_sha256,
    size_bytes,
    COALESCE(source_version, '')::text AS source_version
FROM font_sources
WHERE family_id = $1 AND weight = $2
`

type GetFontSourceRow struct {
	FamilyID       string `json:"family_id"`
	Weight         int16  `json:"weight"`
	Format         string `json:"format"`
	ObjectKey      string `json:"object_key"`
	ChecksumSha256 string `json:"checksum_sha256"`
	SizeBytes      int64  `json:"size_bytes"`
	SourceVersion  string `json:"source_version"`
}

func (q *Queries) GetFontSource(ctx context.Context, familyID string, weight int16) (GetFontSourceRow, error) {
	row := q.db.QueryRow(ctx, getFontSource, familyID, weight)
	var i GetFontSourceRow
	err := row.Scan(
		&i.FamilyID,
		&i.Weight,
		&i.Format,
		&i.ObjectKey,
		&i.ChecksumSha256,
		&i.SizeBytes,
		&i.SourceVersion,
	)
	return i, err
}

const getStaticPackSnapshot = `-- name: GetStaticPackSnapshot :many
WITH current_version AS MATERIALIZED (
    SELECT bullet AS version
    FROM version
    ORDER BY start DESC, bullet DESC
    LIMIT 1
), requested_characters AS MATERIALIZED (
    SELECT DISTINCT requested.character
    FROM unnest($2::text[]) AS requested(character)
), matched_characters AS MATERIALIZED (
    SELECT DISTINCT fonts.char, fonts.pack
    FROM static_fonts AS fonts
    JOIN requested_characters AS requested ON requested.character = fonts.char
    WHERE $1::text = ANY(fonts.families)
), requested_packs AS MATERIALIZED (
    SELECT DISTINCT pack
    FROM matched_characters
), pack_contents AS (
    SELECT
        fonts.pack,
        COALESCE(string_agg(fonts.char, '' ORDER BY fonts.char), '')::text AS characters
    FROM static_fonts AS fonts
    JOIN requested_packs USING (pack)
    WHERE $1::text = ANY(fonts.families)
    GROUP BY fonts.pack
)
SELECT
    current_version.version,
    pack_contents.pack,
    pack_contents.characters,
    NOT EXISTS (
        SELECT 1
        FROM requested_characters AS requested
        WHERE NOT EXISTS (
            SELECT 1
            FROM matched_characters AS matched
            WHERE matched.char = requested.character
        )
    )::boolean AS coverage_complete
FROM current_version
CROSS JOIN pack_contents
ORDER BY pack_contents.pack
`

type GetStaticPackSnapshotRow struct {
	Version          int32       `json:"version"`
	Pack             int16       `json:"pack"`
	Characters       string      `json:"characters"`
	CoverageComplete pgtype.Bool `json:"coverage_complete"`
}

func (q *Queries) GetStaticPackSnapshot(ctx context.Context, column1 string, column2 []string) ([]GetStaticPackSnapshotRow, error) {
	rows, err := q.db.Query(ctx, getStaticPackSnapshot, column1, column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStaticPackSnapshotRow{}
	for rows.Next() {
		var i GetStaticPackSnapshotRow
		if err := rows.Scan(
			&i.Version,
			&i.Pack,
			&i.Characters,
			&i.CoverageComplete,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFontFamilies = `-- name: ListFontFamilies :many
SELECT
    id,
    name,
    COALESCE(name_zh, '')::text AS name_zh,
    COALESCE(name_en, '')::text AS name_en,
    COALESCE(weights, ARRAY[]::SMALLINT[])::SMALLINT[] AS weights,
    COALESCE(license, '')::text AS license,
    COALESCE(version, '')::text AS version,
    COALESCE(description, '')::text AS description,
    COALESCE(category, '')::text AS category,
    COALESCE(family, '')::text AS family,
    COALESCE(tags, ARRAY[]::TEXT[])::TEXT[] AS tags,
    COALESCE(repo_url, '')::text AS repo_url,
    COALESCE(authors, ARRAY[]::TEXT[])::TEXT[] AS authors,
    COALESCE(format, 'ttf')::text AS format,
    COALESCE(demo_content_id, 0)::int AS demo_content_id
FROM font_family
WHERE id > $1::text
  AND (
       $2::text = ''
       OR id ILIKE '%' || $2 || '%'
       OR name ILIKE '%' || $2 || '%'
       OR COALESCE(name_zh, '') ILIKE '%' || $2 || '%'
       OR COALESCE(name_en, '') ILIKE '%' || $2 || '%'
       OR EXISTS (
        SELECT 1
        FROM unnest(COALESCE(authors, ARRAY[]::TEXT[])) AS author
        WHERE author ILIKE '%' || $2 || '%'
       )
   )
ORDER BY id
LIMIT $3::int
`

type ListFontFamiliesParams struct {
	AfterID   string `json:"after_id"`
	Search    string `json:"search"`
	PageLimit int32  `json:"page_limit"`
}

type ListFontFamiliesRow struct {
	ID            string   `json:"id"`
	Name          string   `json:"name"`
	NameZh        string   `json:"name_zh"`
	NameEn        string   `json:"name_en"`
	Weights       []int16  `json:"weights"`
	License       string   `json:"license"`
	Version       string   `json:"version"`
	Description   string   `json:"description"`
	Category      string   `json:"category"`
	Family        string   `json:"family"`
	Tags          []string `json:"tags"`
	RepoUrl       string   `json:"repo_url"`
	Authors       []string `json:"authors"`
	Format        string   `json:"format"`
	DemoContentID int32    `json:"demo_content_id"`
}

func (q *Queries) ListFontFamilies(ctx context.Context, arg ListFontFamiliesParams) ([]ListFontFamiliesRow, error) {
	rows, err := q.db.Query(ctx, listFontFamilies, arg.AfterID, arg.Search, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFontFamiliesRow{}
	for rows.Next() {
		var i ListFontFamiliesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameZh,
			&i.NameEn,
			&i.Weights,
			&i.License,
			&i.Version,
			&i.Description,
			&i.Category,
			&i.Family,
			&i.Tags,
			&i.RepoUrl,
			&i.Authors,
			&i.Format,
			&i.DemoContentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockFontArtifactAdmission = `-- name: LockFontArtifactAdmission :exec
SELECT artifact_count
FROM font_artifact_quota
WHERE singleton
FOR UPDATE
`

func (q *Queries) LockFontArtifactAdmission(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockFontArtifactAdmission)
	return err
}

const markFontArtifactMissing = `-- name: MarkFontArtifactMissing :one
WITH quota AS MATERIALIZED (
    SELECT artifact_count, accounted_bytes
    FROM font_artifact_quota
    WHERE singleton
    FOR UPDATE
), candidate AS MATERIALIZED (
    SELECT artifact.artifact_key, artifact.size_bytes, artifact.reservation_bytes
    FROM font_artifacts AS artifact
    CROSS JOIN quota
    WHERE artifact.artifact_key = $1
      AND artifact.status = 'ready'
      AND artifact.object_key = $2
      AND artifact.generation = $3
      AND quota.artifact_count >= 0
    FOR UPDATE OF artifact
), decision AS MATERIALIZED (
    SELECT CASE
        WHEN candidate.artifact_key IS NULL THEN 'stale'
        WHEN quota.accounted_bytes
             + candidate.reservation_bytes - candidate.size_bytes >
             $4::bigint THEN 'capacity'
        ELSE 'marked'
    END::text AS outcome
    FROM quota
    LEFT JOIN candidate ON TRUE
), marked AS (
    UPDATE font_artifacts AS artifact
    SET status = 'missing', failure_code = NULL, error = $5, updated_at = now()
    FROM candidate
    JOIN decision ON decision.outcome = 'marked'
    WHERE artifact.artifact_key = candidate.artifact_key
    RETURNING artifact.artifact_key
)
SELECT CASE
    WHEN decision.outcome = 'marked' AND marked.artifact_key IS NULL THEN 'stale'
    ELSE decision.outcome
END::text AS result
FROM decision
LEFT JOIN marked ON TRUE
`

type MarkFontArtifactMissingParams struct {
	ArtifactKey       string      `json:"artifact_key"`
	ObjectKey         string      `json:"object_key"`
	Generation        int64       `json:"generation"`
	MaxAccountedBytes int64       `json:"max_accounted_bytes"`
	Error             pgtype.Text `json:"error"`
}

func (q *Queries) MarkFontArtifactMissing(ctx context.Context, arg MarkFontArtifactMissingParams) (string, error) {
	row := q.db.QueryRow(ctx, markFontArtifactMissing,
		arg.ArtifactKey,
		arg.ObjectKey,
		arg.Generation,
		arg.MaxAccountedBytes,
		arg.Error,
	)
	var result string
	err := row.Scan(&result)
	return result, err
}

const markFontArtifactReady = `-- name: MarkFontArtifactReady :one
WITH quota AS MATERIALIZED (
    SELECT artifact_count
    FROM font_artifact_quota
    WHERE singleton
    FOR UPDATE
), claimed_job AS MATERIALIZED (
    SELECT job.artifact_key
    FROM font_build_jobs AS job
    CROSS JOIN quota
    WHERE job.artifact_key = $2
      AND job.status = 'running'
      AND job.locked_by = $3
      AND job.fence = $4
      AND job.lease_until >= now()
      AND quota.artifact_count >= 0
    FOR UPDATE OF job
), candidate AS MATERIALIZED (
    SELECT artifact.artifact_key, artifact.reservation_bytes
    FROM font_artifacts AS artifact
    JOIN claimed_job USING (artifact_key)
    WHERE artifact.artifact_key = $2
      AND artifact.status = 'running'
    FOR UPDATE OF artifact
), completed_job AS (
    UPDATE font_build_jobs AS job
    SET
        status = 'ready',
        locked_by = NULL,
        lease_until = NULL,
        next_attempt_at = NULL,
        retryable = TRUE,
        failure_code = NULL,
        error = NULL,
        completed_at = now(),
        updated_at = now()
    FROM candidate
    WHERE job.artifact_key = candidate.artifact_key
      AND $1::bigint <= candidate.reservation_bytes
    RETURNING job.artifact_key
), published AS (
    UPDATE font_artifacts AS artifact
    SET
        status = 'ready',
        object_key = $5,
        object_version_id = NULLIF($6::text, ''),
        size_bytes = $1,
        etag = NULLIF($7::text, ''),
        checksum_sha256 = NULLIF($8::text, ''),
        generation = $4,
        failure_code = NULL,
        retired_at = NULL,
        error = NULL,
        last_verified_at = now(),
        updated_at = now()
    FROM completed_job
    WHERE artifact.artifact_key = completed_job.artifact_key
    RETURNING artifact.artifact_key
)
SELECT CASE
    WHEN EXISTS (SELECT 1 FROM published) THEN 'ready'
    WHEN EXISTS (
        SELECT 1 FROM candidate
        WHERE $1::bigint > candidate.reservation_bytes
    ) THEN 'capacity'
    ELSE 'not_ready'
END::text AS result
`

type MarkFontArtifactReadyParams struct {
	SizeBytes       int64       `json:"size_bytes"`
	ArtifactKey     string      `json:"artifact_key"`
	LockedBy        pgtype.Text `json:"locked_by"`
	Fence           int64       `json:"fence"`
	ObjectKey       string      `json:"object_key"`
	ObjectVersionID string      `json:"object_version_id"`
	Etag            string      `json:"etag"`
	ChecksumSha256  string      `json:"checksum_sha256"`
}

func (q *Queries) MarkFontArtifactReady(ctx context.Context, arg MarkFontArtifactReadyParams) (string, error) {
	row := q.db.QueryRow(ctx, markFontArtifactReady,
		arg.SizeBytes,
		arg.ArtifactKey,
		arg.LockedBy,
		arg.Fence,
		arg.ObjectKey,
		arg.ObjectVersionID,
		arg.Etag,
		arg.ChecksumSha256,
	)
	var result string
	err := row.Scan(&result)
	return result, err
}

const retireFontArtifacts = `-- name: RetireFontArtifacts :execrows
WITH quota AS MATERIALIZED (
    SELECT artifact_count
    FROM font_artifact_quota
    WHERE singleton
    FOR UPDATE
), locked_job_candidates AS MATERIALIZED (
    SELECT job.artifact_key, artifact.updated_at
    FROM font_build_jobs AS job
    JOIN font_artifacts AS artifact ON artifact.artifact_key = job.artifact_key
    CROSS JOIN quota
    WHERE quota.artifact_count >= 0
      AND (
          (
              artifact.status IN ('pending', 'ready', 'failed', 'missing')
              AND artifact.updated_at < $2::timestamptz
          )
          OR (
              artifact.status = 'running'
              AND artifact.updated_at < $2::timestamptz
              AND job.status = 'running'
              AND job.lease_until < now()
          )
          OR (artifact.status = 'stale' AND artifact.retired_at IS NULL)
      )
    ORDER BY artifact.updated_at, artifact.artifact_key
    LIMIT $3::int
    FOR UPDATE OF job SKIP LOCKED
), no_job_candidates AS MATERIALIZED (
    SELECT artifact.artifact_key, artifact.updated_at
    FROM font_artifacts AS artifact
    CROSS JOIN quota
    WHERE quota.artifact_count >= 0
      AND (
            (
                artifact.status IN ('pending', 'ready', 'failed', 'missing')
                AND artifact.updated_at < $2::timestamptz
            )
            OR (artifact.status = 'stale' AND artifact.retired_at IS NULL)
        )
      AND NOT EXISTS (
          SELECT 1
          FROM font_build_jobs AS job
          WHERE job.artifact_key = artifact.artifact_key
      )
    ORDER BY artifact.updated_at, artifact.artifact_key
    LIMIT $3::int
), selected_candidates AS MATERIALIZED (
    SELECT candidate_pool.artifact_key, candidate_pool.updated_at
    FROM (
        SELECT artifact_key, updated_at FROM locked_job_candidates
        UNION ALL
        SELECT artifact_key, updated_at FROM no_job_candidates
    ) AS candidate_pool
    ORDER BY candidate_pool.updated_at, candidate_pool.artifact_key
    LIMIT $3::int
), candidates AS MATERIALIZED (
    SELECT artifact.artifact_key
    FROM font_artifacts AS artifact
    JOIN selected_candidates USING (artifact_key)
    WHERE (
            (
                artifact.status IN ('pending', 'ready', 'failed', 'missing')
                AND artifact.updated_at < $2::timestamptz
            )
            OR (
                artifact.status = 'running'
                AND artifact.updated_at < $2::timestamptz
                AND EXISTS (
                    SELECT 1
                    FROM locked_job_candidates AS locked_job
                    JOIN font_build_jobs AS job USING (artifact_key)
                    WHERE locked_job.artifact_key = artifact.artifact_key
                      AND job.status = 'running'
                      AND job.lease_until < now()
                )
            )
            OR (artifact.status = 'stale' AND artifact.retired_at IS NULL)
        )
      AND (
          EXISTS (
              SELECT 1 FROM locked_job_candidates AS locked_job
              WHERE locked_job.artifact_key = artifact.artifact_key
          )
          OR NOT EXISTS (
              SELECT 1 FROM font_build_jobs AS job
              WHERE job.artifact_key = artifact.artifact_key
          )
      )
    ORDER BY selected_candidates.updated_at, artifact.artifact_key
    FOR UPDATE OF artifact SKIP LOCKED
), retired_jobs AS (
    UPDATE font_build_jobs AS job
    SET
        status = 'failed',
        locked_by = NULL,
        lease_until = NULL,
        next_attempt_at = now(),
        retryable = TRUE,
        failure_code = NULL,
        error = 'expired build retired by cleanup',
        completed_at = now(),
        updated_at = now()
    FROM candidates
    JOIN locked_job_candidates USING (artifact_key)
    WHERE job.artifact_key = candidates.artifact_key
      AND job.status = 'running'
      AND job.lease_until < now()
    RETURNING job.artifact_key
)
UPDATE font_artifacts AS artifact
SET
    status = 'stale',
    retired_at = $1::timestamptz,
    updated_at = $1::timestamptz
FROM candidates
WHERE artifact.artifact_key = candidates.artifact_key
  AND (
        (
            artifact.status IN ('pending', 'ready', 'failed', 'missing')
            AND artifact.updated_at < $2::timestamptz
        )
        OR (
            artifact.status = 'running'
            AND artifact.updated_at < $2::timestamptz
            AND EXISTS (
                SELECT 1 FROM retired_jobs WHERE retired_jobs.artifact_key = artifact.artifact_key
            )
        )
        OR (artifact.status = 'stale' AND artifact.retired_at IS NULL)
    )
`

type RetireFontArtifactsParams struct {
	RetiredAt      pgtype.Timestamptz `json:"retired_at"`
	InactiveBefore pgtype.Timestamptz `json:"inactive_before"`
	BatchSize      int32              `json:"batch_size"`
}

func (q *Queries) RetireFontArtifacts(ctx context.Context, arg RetireFontArtifactsParams) (int64, error) {
	result, err := q.db.Exec(ctx, retireFontArtifacts, arg.RetiredAt, arg.InactiveBefore, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchFontArtifact = `-- name: TouchFontArtifact :one
WITH touched AS (
    UPDATE font_artifacts AS artifact
    SET updated_at = now(), last_verified_at = now()
    WHERE artifact.artifact_key = $1
      AND artifact.status = 'ready'
      AND artifact.object_key = $2
      AND artifact.generation = $3
      AND artifact.updated_at < now() - ($4::bigint * interval '1 millisecond')
    RETURNING artifact.artifact_key
)
SELECT EXISTS (
    SELECT 1
    FROM font_artifacts AS current_artifact
    WHERE current_artifact.artifact_key = $1
      AND current_artifact.status = 'ready'
      AND current_artifact.object_key = $2
      AND current_artifact.generation = $3
)::boolean AS current
`

type TouchFontArtifactParams struct {
	ArtifactKey       string `json:"artifact_key"`
	ObjectKey         string `json:"object_key"`
	Generation        int64  `json:"generation"`
	MinimumIntervalMs int64  `json:"minimum_interval_ms"`
}

func (q *Queries) TouchFontArtifact(ctx context.Context, arg TouchFontArtifactParams) (bool, error) {
	row := q.db.QueryRow(ctx, touchFontArtifact,
		arg.ArtifactKey,
		arg.ObjectKey,
		arg.Generation,
		arg.MinimumIntervalMs,
	)
	var current bool
	err := row.Scan(&current)
	return current, err
}
