// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DemoSentence struct {
	Sid      int32       `json:"sid"`
	Content  pgtype.Text `json:"content"`
	Language pgtype.Text `json:"language"`
}

type FontArtifact struct {
	ArtifactKey             string             `json:"artifact_key"`
	Kind                    string             `json:"kind"`
	Status                  string             `json:"status"`
	FamilyID                string             `json:"family_id"`
	Weight                  int16              `json:"weight"`
	Version                 pgtype.Int4        `json:"version"`
	Pack                    pgtype.Text        `json:"pack"`
	WordHash                pgtype.Text        `json:"word_hash"`
	NormalizedWordSet       pgtype.Text        `json:"normalized_word_set"`
	SourceChecksumSha256    pgtype.Text        `json:"source_checksum_sha256"`
	BuilderVersion          string             `json:"builder_version"`
	ObjectKey               string             `json:"object_key"`
	ContentType             string             `json:"content_type"`
	SizeBytes               int64              `json:"size_bytes"`
	Etag                    pgtype.Text        `json:"etag"`
	ChecksumSha256          pgtype.Text        `json:"checksum_sha256"`
	Error                   pgtype.Text        `json:"error"`
	LastVerifiedAt          pgtype.Timestamptz `json:"last_verified_at"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	Generation              int64              `json:"generation"`
	ArtifactProtocolVersion string             `json:"artifact_protocol_version"`
	RetiredAt               pgtype.Timestamptz `json:"retired_at"`
	ObjectVersionID         pgtype.Text        `json:"object_version_id"`
	FailureCode             pgtype.Text        `json:"failure_code"`
	ReservationBytes        int64              `json:"reservation_bytes"`
	QuotaBytes              pgtype.Int8        `json:"quota_bytes"`
}

type FontArtifactQuotum struct {
	Singleton      bool  `json:"singleton"`
	ArtifactCount  int64 `json:"artifact_count"`
	AccountedBytes int64 `json:"accounted_bytes"`
}

type FontBuildJob struct {
	ID            int64              `json:"id"`
	ArtifactKey   string             `json:"artifact_key"`
	Status        string             `json:"status"`
	Attempts      int64              `json:"attempts"`
	LockedBy      pgtype.Text        `json:"locked_by"`
	LeaseUntil    pgtype.Timestamptz `json:"lease_until"`
	Error         pgtype.Text        `json:"error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	Fence         int64              `json:"fence"`
	Retryable     bool               `json:"retryable"`
	FailureCode   pgtype.Text        `json:"failure_code"`
}

type FontFamily struct {
	ID            string      `json:"id"`
	Name          string      `json:"name"`
	NameZh        pgtype.Text `json:"name_zh"`
	NameEn        pgtype.Text `json:"name_en"`
	Weights       []int16     `json:"weights"`
	License       pgtype.Text `json:"license"`
	Version       pgtype.Text `json:"version"`
	Description   pgtype.Text `json:"description"`
	Category      pgtype.Text `json:"category"`
	Family        pgtype.Text `json:"family"`
	Tags          []string    `json:"tags"`
	RepoUrl       pgtype.Text `json:"repo_url"`
	Authors       []string    `json:"authors"`
	Languages     []byte      `json:"languages"`
	DemoContentID pgtype.Int4 `json:"demo_content_id"`
	Format        string      `json:"format"`
}

type FontSource struct {
	ID             int64              `json:"id"`
	FamilyID       string             `json:"family_id"`
	Weight         int16              `json:"weight"`
	Format         string             `json:"format"`
	ObjectKey      string             `json:"object_key"`
	ChecksumSha256 pgtype.Text        `json:"checksum_sha256"`
	SizeBytes      int64              `json:"size_bytes"`
	SourceVersion  pgtype.Text        `json:"source_version"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type FontTerminalFailure struct {
	ArtifactKey             string             `json:"artifact_key"`
	Kind                    string             `json:"kind"`
	FamilyID                string             `json:"family_id"`
	Weight                  int16              `json:"weight"`
	Version                 pgtype.Int4        `json:"version"`
	Pack                    pgtype.Text        `json:"pack"`
	WordHash                pgtype.Text        `json:"word_hash"`
	NormalizedWordSet       pgtype.Text        `json:"normalized_word_set"`
	SourceChecksumSha256    pgtype.Text        `json:"source_checksum_sha256"`
	BuilderVersion          string             `json:"builder_version"`
	ArtifactProtocolVersion string             `json:"artifact_protocol_version"`
	ContentType             string             `json:"content_type"`
	FailureCode             string             `json:"failure_code"`
	Error                   pgtype.Text        `json:"error"`
	CachedAt                pgtype.Timestamptz `json:"cached_at"`
}

type StaticFont struct {
	Char     string   `json:"char"`
	Pack     int16    `json:"pack"`
	Families []string `json:"families"`
	UseCount int32    `json:"use_count"`
}

// Small key/value table for backend system metadata.
type SystemMetadatum struct {
	// Stable metadata key.
	MetadataKey string `json:"metadata_key"`
	// Metadata value encoded by the caller.
	MetadataValue string             `json:"metadata_value"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Version struct {
	Bullet int32              `json:"bullet"`
	Start  pgtype.Timestamptz `json:"start"`
}
