// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcquireFontBuildJob(ctx context.Context, arg AcquireFontBuildJobParams) (bool, error)
	CompleteFontBuildJob(ctx context.Context, artifactKey string, lockedBy pgtype.Text) (int64, error)
	CreateFontArtifact(ctx context.Context, arg CreateFontArtifactParams) error
	DeleteSystemMetadata(ctx context.Context, metadataKey string) error
	FailFontBuildJob(ctx context.Context, arg FailFontBuildJobParams) (int64, error)
	FindStaticPacks(ctx context.Context, column1 string, column2 []string) ([]int16, error)
	GetCurrentStaticVersion(ctx context.Context) (int32, error)
	GetFontArtifact(ctx context.Context, artifactKey string) (GetFontArtifactRow, error)
	GetFontFamily(ctx context.Context, id string) (GetFontFamilyRow, error)
	GetFontSource(ctx context.Context, familyID string, weight int16) (GetFontSourceRow, error)
	GetStaticPackCharacters(ctx context.Context, pack int16, column2 string) (string, error)
	GetSystemMetadataValue(ctx context.Context, metadataKey string) (string, error)
	ListFontFamilies(ctx context.Context, dollar_1 string) ([]ListFontFamiliesRow, error)
	MarkFontArtifactFailed(ctx context.Context, arg MarkFontArtifactFailedParams) (int64, error)
	MarkFontArtifactMissing(ctx context.Context, artifactKey string, error pgtype.Text) error
	MarkFontArtifactReady(ctx context.Context, arg MarkFontArtifactReadyParams) (int64, error)
	SetSystemMetadataValue(ctx context.Context, metadataKey string, metadataValue string) error
}

var _ Querier = (*Queries)(nil)
