// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcquireFontBuildJob(ctx context.Context, arg AcquireFontBuildJobParams) (int64, error)
	CreateFontArtifact(ctx context.Context, arg CreateFontArtifactParams) (string, error)
	DeleteRetiredFontArtifacts(ctx context.Context, retiredBefore pgtype.Timestamptz, batchSize int32) (int64, error)
	DeleteSystemMetadata(ctx context.Context, metadataKey string) error
	FailFontBuildJob(ctx context.Context, arg FailFontBuildJobParams) (int64, error)
	FailFontBuildJobTerminal(ctx context.Context, arg FailFontBuildJobTerminalParams) (int64, error)
	FindReferencedFontObjectKeys(ctx context.Context, objectKeys []string) ([]string, error)
	GetFontArtifact(ctx context.Context, artifactKey string) (GetFontArtifactRow, error)
	GetFontBuildRetryAfterSeconds(ctx context.Context, artifactKey string) (int64, error)
	GetFontFamily(ctx context.Context, id string) (GetFontFamilyRow, error)
	GetFontSource(ctx context.Context, familyID string, weight int16) (GetFontSourceRow, error)
	GetStaticPackSnapshot(ctx context.Context, column1 string, column2 []string) ([]GetStaticPackSnapshotRow, error)
	GetSystemMetadataValue(ctx context.Context, metadataKey string) (string, error)
	ListFontFamilies(ctx context.Context, arg ListFontFamiliesParams) ([]ListFontFamiliesRow, error)
	LockFontArtifactAdmission(ctx context.Context) error
	MarkFontArtifactMissing(ctx context.Context, arg MarkFontArtifactMissingParams) (string, error)
	MarkFontArtifactReady(ctx context.Context, arg MarkFontArtifactReadyParams) (string, error)
	RetireFontArtifacts(ctx context.Context, arg RetireFontArtifactsParams) (int64, error)
	SetSystemMetadataValue(ctx context.Context, metadataKey string, metadataValue string) error
	TouchFontArtifact(ctx context.Context, arg TouchFontArtifactParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
