// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: system_metadata.sql

package sqlc

import (
	"context"
)

const deleteSystemMetadata = `-- name: DeleteSystemMetadata :exec
DELETE FROM system_metadata
WHERE metadata_key = $1
`

func (q *Queries) DeleteSystemMetadata(ctx context.Context, metadataKey string) error {
	_, err := q.db.Exec(ctx, deleteSystemMetadata, metadataKey)
	return err
}

const getSystemMetadataValue = `-- name: GetSystemMetadataValue :one
SELECT metadata_value
FROM system_metadata
WHERE metadata_key = $1
`

func (q *Queries) GetSystemMetadataValue(ctx context.Context, metadataKey string) (string, error) {
	row := q.db.QueryRow(ctx, getSystemMetadataValue, metadataKey)
	var metadata_value string
	err := row.Scan(&metadata_value)
	return metadata_value, err
}

const setSystemMetadataValue = `-- name: SetSystemMetadataValue :exec
INSERT INTO system_metadata (
    metadata_key,
    metadata_value
) VALUES (
    $1,
    $2
)
ON CONFLICT (metadata_key) DO UPDATE
SET
    metadata_value = EXCLUDED.metadata_value,
    updated_at = now()
`

func (q *Queries) SetSystemMetadataValue(ctx context.Context, metadataKey string, metadataValue string) error {
	_, err := q.db.Exec(ctx, setSystemMetadataValue, metadataKey, metadataValue)
	return err
}
