CREATE TABLE IF NOT EXISTS admin_users (
    user_id TEXT PRIMARY KEY,
    password_hash TEXT NOT NULL,
    last_login TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
